const dict={
'en':{
'nav.home':'Home','nav.treatments':'Treatments','nav.clinic':'Clinic','nav.contact':'Contact','header.call':'Call clinic','hero.eyebrow':'DENTISTRY / AMSTERDAM','hero.title':'A calmer way to care for your <em>smile.</em>','hero.text':'Modern dentistry built around precision, comfort and honest conversations. No rush. No noise. Just thoughtful care.','hero.cta':'Meet the clinic','hero.secondary':'Explore treatments →','hero.note1':'Gentle care','hero.note2':'Clear guidance','hero.note3':'Modern craft','hero.cardTitle':'Open today','hero.cardText':'09:00 — 18:00','hero.alt':'Modern dental chair and soft clinic interior','statement.title':'Healthy can feel <span>beautifully simple.</span>','statement.text':'From preventive care to restorative treatments, every detail is designed to make your visit feel more human.','feature1.kicker':'PREVENTIVE','feature1.title':'Keep the small things small.','feature1.text':'Regular hygiene, examinations and practical advice that fit real life.','feature2.kicker':'RESTORATIVE','feature2.title':'Natural-looking, considered work.','feature2.text':'Conservative solutions for teeth that need a little more attention.','feature3.kicker':'AESTHETIC','feature3.title':'Subtle changes. More confidence.','feature3.text':'Whitening and smile-focused treatments with a light touch.','common.read':'View care →','quote':'Good dentistry should feel less like a procedure and more like being looked after.','quoteBy':'— IVORY clinical philosophy','strip.kicker':'COME BY','strip.title':'Your smile deserves a room that feels calm.','strip.cta':'Contact details','footer.tag':'Contemporary dental care, thoughtfully delivered.',
'treat.headKicker':'CARE / TREATMENTS','treat.title':'Thoughtful dentistry,<br><em>without the jargon.</em>','treat.intro':'A focused range of dental care, explained clearly and delivered with a conservative approach.','tr1.kicker':'PREVENTIVE CARE','tr1.title':'Exams & hygiene','tr1.text':'Professional cleaning, oral examinations and practical routines for long-term dental health.','tr1.tag1':'Cleaning','tr1.tag2':'Examination','tr1.tag3':'Advice','tr2.kicker':'RESTORATIVE','tr2.title':'Fillings & crowns','tr2.text':'Carefully planned restorative work designed to protect structure and keep your smile natural.','tr2.tag1':'Composite','tr2.tag2':'Crowns','tr2.tag3':'Repairs','tr3.kicker':'AESTHETIC','tr3.title':'Whitening & smile care','tr3.text':'Subtle cosmetic options for a brighter, more even smile—always matched to your starting point.','tr3.tag1':'Whitening','tr3.tag2':'Smile review','tr3.tag3':'Guidance','tr4.kicker':'GUM HEALTH','tr4.title':'Periodontal care','tr4.text':'Gentle, structured care for gums that need closer attention and a clearer maintenance plan.','tr4.tag1':'Gum care','tr4.tag2':'Monitoring','tr4.tag3':'Maintenance','treat.note':'Treatment needs are personal. We explain the options available to you during your visit so you can make an informed choice.',
'clinic.kicker':'THE CLINIC','clinic.title':'A small practice<br>with <em>big attention</em>.','clinic.text':'IVORY is designed around a simple idea: the environment matters. Soft light, considered materials and enough time to explain what is happening.','clinic.alt':'Warm contemporary dental clinic interior','p1.title':'Listen first.','p1.text':'We start with your concerns, not a script.','p2.title':'Explain clearly.','p2.text':'You should understand your options before choosing a direction.','p3.title':'Treat thoughtfully.','p3.text':'We aim for durable, natural-looking results without unnecessary complexity.','team.kicker':'CLINICAL TEAM','team.title':'Experienced hands.<br><em>Human approach.</em>','team.text':'Our clinicians combine modern techniques with a calm, conversational way of working.','team.cta':'Talk to the clinic →','team.alt':'Portrait illustration of a dentist',
'contact.kicker':'CONTACT / VISIT','contact.title':'Let’s make your next visit<br><em>feel easy.</em>','contact.text':'For questions or to speak with the clinic, call us or send an email. We’ll be happy to help.','contact.phoneLabel':'Phone','contact.emailLabel':'Email','contact.addressLabel':'Address','contact.hoursLabel':'Hours','contact.hours':'Mon — Fri / 09:00 — 18:00','visit.kicker':'WHEN YOU ARRIVE','visit.title':'A simple welcome.','visit.text':'The clinic is in central Amsterdam, close to public transport and easy to reach on foot or by bicycle.','visit.map':'Open map','map.alt':'Stylized map card showing the clinic area'
},
'ar':{
'nav.home':'الرئيسية','nav.treatments':'العلاجات','nav.clinic':'العيادة','nav.contact':'تواصل معنا','header.call':'اتصل بالعيادة','hero.eyebrow':'طب الأسنان / أمستردام','hero.title':'طريقة أكثر هدوءًا للاهتمام <em>بابتسامتك.</em>','hero.text':'طب أسنان حديث قائم على الدقة والراحة والحوار الواضح. بلا استعجال. بلا ضوضاء. فقط عناية مدروسة.','hero.cta':'تعرّف على العيادة','hero.secondary':'استكشف العلاجات ←','hero.note1':'عناية لطيفة','hero.note2':'إرشاد واضح','hero.note3':'تقنيات حديثة','hero.cardTitle':'مفتوح اليوم','hero.cardText':'09:00 — 18:00','hero.alt':'كرسي أسنان حديث وداخل عيادة هادئ','statement.title':'الصحة يمكن أن تكون <span>ببساطة جميلة.</span>','statement.text':'من العناية الوقائية إلى العلاجات الترميمية، صممنا كل تفصيلة لتجعل زيارتك أكثر إنسانية.','feature1.kicker':'وقائية','feature1.title':'خلّي التفاصيل الصغيرة تفضل صغيرة.','feature1.text':'تنظيف وفحوصات ونصائح عملية تناسب حياتك اليومية.','feature2.kicker':'ترميمية','feature2.title':'نتائج طبيعية ومدروسة.','feature2.text':'حلول محافظة للأسنان التي تحتاج إلى مزيد من الاهتمام.','feature3.kicker':'تجميلية','feature3.title':'تغييرات بسيطة. ثقة أكبر.','feature3.text':'تبييض وعلاجات تركز على الابتسامة بلمسة خفيفة.','common.read':'شاهد العناية ←','quote':'طب الأسنان الجيد يجب أن يكون أقل شبهًا بالإجراء وأكثر شبهًا بالشعور بأن هناك من يهتم بك.','quoteBy':'— فلسفة عيادة IVORY','strip.kicker':'نرحب بك','strip.title':'ابتسامتك تستحق مكانًا تشعر فيه بالهدوء.','strip.cta':'بيانات التواصل','footer.tag':'رعاية أسنان عصرية، تُقدَّم باهتمام.',
'treat.headKicker':'العناية / العلاجات','treat.title':'طب أسنان مدروس،<br><em>من غير تعقيد.</em>','treat.intro':'مجموعة مركزة من خدمات الأسنان، نشرحها بوضوح ونقدمها بأسلوب محافظ ومدروس.','tr1.kicker':'العناية الوقائية','tr1.title':'الفحوصات والتنظيف','tr1.text':'تنظيف احترافي وفحوصات للفم وروتين عملي لصحة الأسنان على المدى الطويل.','tr1.tag1':'تنظيف','tr1.tag2':'فحص','tr1.tag3':'نصائح','tr2.kicker':'العلاجات الترميمية','tr2.title':'الحشوات والتيجان','tr2.text':'علاجات ترميمية مخططة بعناية لحماية بنية السن والحفاظ على شكل ابتسامتك الطبيعي.','tr2.tag1':'حشوات تجميلية','tr2.tag2':'تيجان','tr2.tag3':'إصلاحات','tr3.kicker':'العناية التجميلية','tr3.title':'التبييض والعناية بالابتسامة','tr3.text':'خيارات تجميلية بسيطة لابتسامة أكثر إشراقًا وتناسقًا، بما يناسب حالتك الحالية.','tr3.tag1':'تبييض','tr3.tag2':'مراجعة الابتسامة','tr3.tag3':'إرشاد','tr4.kicker':'صحة اللثة','tr4.title':'العناية باللثة','tr4.text':'عناية لطيفة ومنظمة للثة التي تحتاج إلى متابعة أقرب وخطة أوضح للحفاظ عليها.','tr4.tag1':'العناية باللثة','tr4.tag2':'متابعة','tr4.tag3':'حفاظ','treat.note':'احتياجات العلاج تختلف من شخص لآخر. نشرح لك الخيارات المناسبة أثناء زيارتك حتى تتمكن من اتخاذ قرار واعٍ.',
'clinic.kicker':'العيادة','clinic.title':'عيادة صغيرة،<br>باهتمام <em>كبير.</em>','clinic.text':'صممنا IVORY حول فكرة بسيطة: المكان مهم. إضاءة هادئة، خامات مدروسة ووقت كافٍ لشرح ما يحدث.','clinic.alt':'داخل عيادة أسنان عصرية ودافئة','p1.title':'نسمعك أولًا.','p1.text':'نبدأ بما يقلقك أنت، وليس من نص محفوظ.','p2.title':'نشرح بوضوح.','p2.text':'من حقك تفهم الخيارات المتاحة قبل اختيار الاتجاه المناسب.','p3.title':'نعالج باهتمام.','p3.text':'هدفنا نتائج طبيعية ومتينة من غير تعقيد غير ضروري.','team.kicker':'الفريق الطبي','team.title':'خبرة في الأيدي.<br><em>وإنسانية في التعامل.</em>','team.text':'يجمع فريقنا بين التقنيات الحديثة وطريقة عمل هادئة وواضحة وقريبة من المريض.','team.cta':'تحدث مع العيادة ←','team.alt':'رسم بورتريه لطبيب أسنان',
'contact.kicker':'تواصل / زيارة','contact.title':'خلّي زيارتك القادمة<br><em>أسهل.</em>','contact.text':'لو عندك سؤال أو حابب تتحدث مع العيادة، اتصل بنا أو أرسل بريدًا إلكترونيًا. يسعدنا مساعدتك.','contact.phoneLabel':'الهاتف','contact.emailLabel':'البريد الإلكتروني','contact.addressLabel':'العنوان','contact.hoursLabel':'المواعيد','contact.hours':'الإثنين — الجمعة / 09:00 — 18:00','visit.kicker':'عند وصولك','visit.title':'ترحيب بسيط.','visit.text':'العيادة في وسط أمستردام، قريبة من المواصلات العامة ويسهل الوصول إليها مشيًا أو بالدراجة.','visit.map':'فتح الخريطة','map.alt':'خريطة فنية توضح منطقة العيادة'
}};
function setLang(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('rtl-only',lang==='ar');document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[lang][key])el.innerHTML=dict[lang][key]});document.querySelectorAll('[data-alt]').forEach(el=>{const key=el.dataset.alt;if(dict[lang][key])el.alt=dict[lang][key]});localStorage.setItem('ivory-lang',lang);const b=document.getElementById('langBtn');if(b)b.textContent=lang==='ar'?'EN':'AR'}
const savedLang=localStorage.getItem('ivory-lang')||'en';setLang(savedLang);
const savedTheme=localStorage.getItem('ivory-theme')||'light';if(savedTheme==='dark')document.documentElement.dataset.theme='dark';
document.getElementById('langBtn')?.addEventListener('click',()=>setLang((localStorage.getItem('ivory-lang')||'en')==='en'?'ar':'en'));
document.getElementById('themeBtn')?.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';if(dark)delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme='dark';localStorage.setItem('ivory-theme',dark?'light':'dark')});
document.getElementById('menuBtn')?.addEventListener('click',()=>document.querySelector('.nav')?.classList.toggle('open'));
